#!/bin/bash
# Generated by AKSFlexNode CheckRouteOverlap. Do not edit. mode={{ .ModeLabel }}
set -eu
PATH=/usr/sbin:/sbin:/usr/bin:/bin:${PATH:-}

mkdir -p /run/aks-flex-node
rm -f /run/aks-flex-node/route-overlap.detected
rm -f /run/aks-flex-node/route-overlap.ok

DEFAULT_DEV=$(ip -4 route show default 2>/dev/null | awk '/^default / {for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')
if [ -z "$DEFAULT_DEV" ]; then
  echo "check-route-overlap: no IPv4 default route; cannot determine outbound interface" >&2
  echo "no-default-route" > /run/aks-flex-node/route-overlap.detected
  exit {{ .FailExit }}
fi

{{- if .HasEntries }}
bad=0
while IFS='|' read -r CIDR PROBE; do
  [ -z "$CIDR" ] && continue
  ACTUAL=$(ip -4 route get "$PROBE" 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')
  if [ -z "$ACTUAL" ]; then ACTUAL="<no-route>"; fi
  if [ "$ACTUAL" != "$DEFAULT_DEV" ]; then
    if [ "$ACTUAL" = "<no-route>" ]; then
      msg="NO-ROUTE: expected CIDR $CIDR (probe $PROBE) has no IPv4 route; expected via $DEFAULT_DEV"
    else
      msg="OVERLAP: expected CIDR $CIDR (probe $PROBE) routes via $ACTUAL, expected $DEFAULT_DEV"
    fi
    echo "$msg" >&2
    echo "$msg" >> /run/aks-flex-node/route-overlap.detected
    bad=1
  fi
done <<'EOF'
{{ .Entries }}
EOF

if [ "$bad" -eq 1 ]; then
  cat >&2 <<'EOF'
Action: configure spec.staticRoutes on the NodeClass with more-specific
routes for the affected CIDRs, or rebuild the cluster on a non-overlapping
VNet CIDR. For each affected CIDR, add a spec.staticRoutes entry with the
destination CIDR and next-hop/default gateway for the node's normal outbound interface.
EOF
  exit {{ .FailExit }}
fi

echo "check-route-overlap: all expected CIDRs route via $DEFAULT_DEV"
touch /run/aks-flex-node/route-overlap.ok
exit 0
{{- else }}
echo "check-route-overlap: no expected CIDRs configured; nothing to check (default dev: $DEFAULT_DEV)"
touch /run/aks-flex-node/route-overlap.ok
exit 0
{{- end }}
