#!/bin/bash
# Generated by AKSFlexNode ConfigureStaticRoutes. Do not edit.
set -eu
PATH=/usr/sbin:/sbin:/usr/bin:/bin:${PATH:-}

# resolve_default_gw <dev>: prints the default gateway for <dev> after retrying
# for up to ~30s, in case cloud-init / DHCP has not installed it yet.
resolve_default_gw() {
  local dev="$1"
  local i gw
  for i in $(seq 1 30); do
    gw=$(ip -4 route show default dev "$dev" 2>/dev/null | awk '/^default via/ {print $3; exit}')
    if [ -n "$gw" ]; then echo "$gw"; return 0; fi
    sleep 1
  done
  return 1
}

# resolve_default_dev: prints the outbound interface of the IPv4 default
# route (e.g. eth0, ens3, enp0s6). Retries up to ~30s for DHCP.
resolve_default_dev() {
  local i dev
  for i in $(seq 1 30); do
    dev=$(ip -4 route show default 2>/dev/null | awk '/^default / {for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')
    if [ -n "$dev" ]; then echo "$dev"; return 0; fi
    sleep 1
  done
  return 1
}

{{- if .HasEntries }}
DEFAULT_DEV=""
resolve_default_dev_cached() {
  if [ -n "$DEFAULT_DEV" ]; then echo "$DEFAULT_DEV"; return 0; fi
  DEFAULT_DEV=$(resolve_default_dev) || return 1
  echo "$DEFAULT_DEV"
}

while IFS='|' read -r DEST DEV GW METRIC; do
  [ -z "$DEST" ] && continue
  if [ "$DEV" = "{{ .AutoDevToken }}" ]; then
    DEV=$(resolve_default_dev_cached) || { echo "no default IPv4 route; cannot install route $DEST" >&2; exit 1; }
  fi
  if [ "$GW" = "{{ .AutoGWToken }}" ]; then
    GW=$(resolve_default_gw "$DEV") || { echo "no default gateway on $DEV after 30s; cannot install route $DEST" >&2; exit 1; }
  fi
  if [ "$METRIC" -gt 0 ]; then
    ip -4 route replace "$DEST" via "$GW" dev "$DEV" metric "$METRIC"
  else
    ip -4 route replace "$DEST" via "$GW" dev "$DEV"
  fi
done <<'EOF'
{{ .Entries }}
EOF
exit 0
{{- else }}
# No routes configured; nothing to do.
exit 0
{{- end }}
